---
ansible_user: cisco
ansible_password: cisco
ansible_connection: network_cli
ansible_network_os: nxos
### Become method only needed if user authorization is too low and escalation is needed ###
#ansible_become: yes
#ansible_become_method: enable
#ansible_become_password: cisco