---
# ansible-playbook for config change

- name: run tasks on all hosts
  hosts: iosxe_routers
  
  tasks:
  - name: Add Login Banner
    ios_banner:
      banner: login
      text: |
        *****************************************************************
        * This is a virtual router used to test cool Network Automation *
        * tasks and other great stuff to make life easier.  Please take *
        * the time to learn these great skillz!                         *
        *****************************************************************
      state: present
  - name: Remove all other Banners
    ios_banner:
#      banner: motd
#      state: absent   
      banner: exec
      state: absent
#      banner: incoming
#      state: absent
