---
# ansible-playbook testing

- name: run tasks on all hosts
  hosts: ios_routers
#  tasks:
#    - debug: var=ansible_host

  tasks:
    - name: gather tasks and disply some output
      cisco.ios.ios_facts:
        gather_subset: all
      register: result

    - name: Disply the config
      debug:
        var: result
