---
# ansible-playbook testing

- name: run tasks on all hosts
  hosts: nxos_switches
#  tasks:
#    - debug: var=ansible_host

  tasks:
    - name: gather tasks and display some output
      nxos_facts:
        gather_subset: all
      register: result

    - name: Display the config
      debug:
        var: result
