---
# ansible-playbook to test ping to google
# https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_ping_module.html#ansible-collections-cisco-ios-ios-ping-module

- name: run tasks on all hosts
  hosts: routers
  
  tasks:
  - name: Test ping to 8.8.8.8
    cisco.ios.ios_ping:
      dest: 8.8.8.8
      vrf: mgmt
      count: 5
    # registers are used when capturing the output of a task to a variable
    register: results

  - name: Print return values
    debug:
      var: results.rtt